
CREATE TABLE IF NOT EXISTS urls (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255) NOT NULL UNIQUE,
                      created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS url_checks (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            url_id BIGINT NOT NULL,
                            status_code INT NOT NULL,
                            h1 TEXT,
                            title TEXT,
                            description TEXT,
                            created_at TIMESTAMP NOT NULL,
                            CONSTRAINT fk_url_checks_url_id FOREIGN KEY (url_id) REFERENCES urls (id) ON DELETE CASCADE
);